- name: Install NGINX 
  apt: 
    name: nginx 
    state: latest 
    update_cache: yes 

- name: Started and Enabled NGINX 
  service: 
    name: nginx 
    enabled: true 
    state: started 

- name: Configure nginx 
  template: 
    src: default.j2 
    dest: "{{ path_nginx }}"
  notify:
    - Restarted NGINX