---
- name: Update all packages
  apt:
    name: "*"
    state: latest
    update_cache: yes
    force_apt_get: yes

- name: Install list of required packages
  apt: 
    name: "{{ required_packages }}"
    state: latest
    update_cache: yes